In [1]:
import requests
import numpy as np
import pandas as pd

def get_stock_info(function, symbol, api_key):
    base_url = 'https://www.alphavantage.co/query?'
    function = f'function={function}&'
    symbol = f'symbol={symbol}&'
    api_key = f'apikey={api_key}'
    query_url = base_url + function + symbol + api_key
    response = requests.get(query_url)
    data = response.json()
    stock_df = pd.DataFrame(data['Time Series (Daily)']).transpose()
    stock_df = stock_df.rename(columns = {'1. open':'Open', '2. high':'High', '3. low':'Low', '4. close':'Close', '5. volume':'Volume'})
    reset_index = stock_df.reset_index()
    reset_index.rename(columns = {'index':'Date'}, inplace = True)
    reset_index = reset_index.astype({'Open':'float', 'High':'float','Low':'float','Close':'float','Volume':'int'})
    reset_index['Date'] = pd.to_datetime(reset_index['Date'], format = 'ISO8601')
    final_df = reset_index
    return final_df

In [14]:
AAPL_df = get_stock_info('TIME_SERIES_DAILY', 'AAPL', 'XXXXXXX')
AAPL_df = AAPL_df.sort_values(by = 'Date')
AAPL_df

         Date     Open      High       Low   Close    Volume
99 2025-11-17  268.815  270.4900  265.7300  267.46  45018260
98 2025-11-18  269.990  270.7100  265.3200  267.44  45677278
97 2025-11-19  265.525  272.2100  265.5000  268.56  40424492
96 2025-11-20  270.830  275.4300  265.9200  266.25  45823568
95 2025-11-21  265.950  273.3300  265.6700  271.49  59030832
..        ...      ...       ...       ...     ...       ...
4  2026-04-07  256.155  256.2000  245.7000  253.50  62148008
3  2026-04-08  258.450  259.7499  256.5300  258.90  41032772
2  2026-04-09  259.000  261.1200  256.0700  260.49  28121574
1  2026-04-10  259.980  262.1900  259.0231  260.48  31291473
0  2026-04-13  259.730  260.1800  256.6600  259.20  35102803

[100 rows x 6 columns]

In [3]:
!pip install --quiet sqlalchemy mysql-connector-python

In [16]:
import sqlalchemy

user = 'Alex'
password = 'Goblin1077!'
host = 'AlexPC'
database = 'test'

engine = sqlalchemy.create_engine(f'mysql+mysqlconnector://{user}:{password}@{host}/{database}')

In [17]:
AAPL_df.to_sql(name = 'aapl', con = engine, if_exists = 'replace', index = False)

100

In [18]:
engine.dispose()

In [19]:
test_df = pd.DataFrame({
    'Date':'2206-04-13',
    'Open':279.980,
    'High':278.890,
    'Low':280.98,
    'Close':232.232,
    'Volume': 25676865
}, index = [0])

In [20]:
test_df

         Date    Open    High     Low    Close    Volume
0  2206-04-13  279.98  278.89  280.98  232.232  25676865

In [21]:
user = 'Alex'
password = 'Goblin1077!'
host = 'AlexPC'
database = 'test'

engine = sqlalchemy.create_engine(f'mysql+mysqlconnector://{user}:{password}@{host}/{database}')

In [22]:
test_df.to_sql(name = 'aapl', con = engine, if_exists = 'append', index = False)

1

In [23]:
engine.dispose()